# Procesamiento Data Conclat

```{r,echo=FALSE,warning=FALSE,message=FALSE}
rm(list=ls())
options(scipen = 999)

library(pacman)
p_load(
  # generacion docs 
  flextable,         # tablas personalizadas para word
  kableExtra,        # mejorar tablas
  knitr,             # generar reportes reproducibles
  officer,           # crear/modifcar documentos word o ppt
  tinytex,           # instalación mínima de LaTeX para generar PDF
  
  # importacion datos 
  haven,             # impotar/exportar datos spss, stata, sas con etiquetas
  readr,             # lectura rápida de csv
  readxl,            # leer excel 
  
  # manipulacion 
  forcats,           # manipulación de factores
  labelled,          # trabajar con variables etiquetadas
  purrr,             # programación funcional para listas y data frames
  sjlabelled,        # manejar etiquetas 
  stringr,           # manipular texto
  sjmisc,            # limpieza y descripción de datos
  
  # visualización
  ggplot2,           # visualización basado en gramática de gráficos
  ggrepel,           # etiquetas en gráficos sin superposición
  gridExtra,         # combinar gráficos en uno solo
  scales,            # controla cómo se ven los ejes en gráficos
  sjPlot,            # visualizar resultados estadísticos
  
  # análisis
  psych,             # análisis general, psicométrico
  survey,            # diseño survey encuestas complejas
  srvyr,             # diseño survey con tidy
  rlang,             # motor interno de tidyverse, para usar expresiones 
  tidyverse,
  statar            # conectar con el lenguaje stata

  # # conexion web
  # curl,              # conexiones http de bajo nivel: para solucionar el problema de la api del ine
  # httr               # cliente http para API
  )
```

## Cargar datos

```{r datos,message=FALSE,warning=FALSE}
data <- readRDS("input/data/datos-clases.rds")
```

## Selección de variables

```{r data,message=FALSE,warning=FALSE}
data <- data %>%
  select(
    # identificacion
    id,
    rake_wb2,
    
    # Demográficas
    e01,                         # sexo
    female,                      # female  
    age,                         # edad
    educ,                        # educación
    
    # Relación con los medios de producción
    a07,                         # employment situation
    relation_mop,                # relation mean of production
    company_size,                # tamaño empresa
    workplace_size,              # tamaño local    
    b19,                         # sindicatos en empresa
    b21,                         # afiliación sindical
    a25_rec,                     # rama

    # Políticas
    c01_01,                      # Importancia: mejores salarios
    c01_02,                      # Importancia: reducir dedsigualdad
    c05_02,                      # Acuerdo: desigualda es porque dueños empresa pagan poco
    c05_03,                      # Acuerdo: alto nivel vida dueños empresas es por pagar poco
    c06_02,                      # Acuerdo: apoyo sistema solidario de reparto
    c07_01,                      # Acuerdo: aumentar impuestos a los más ricos
    c07_03,                      # Acuerdo: sindicatos tengan más poder
    c07_04,                      # Acuerdo: redistribuir riquezas
    c07_05,                      # Acuerdo: igualdad hombres y mujeres
    c07_06,                      # Acuerdo: educación universitaria pública
    c08,                         # posición política
    c10_01,                      # habla de politica con amigos
    c15_01                       # confia en partidos políticos
  )
```

## Procesamiento

### Demográficas

#### gender

```{r}
frq(data$e01)

data <- data %>%
  mutate(
    gender = factor(
      e01, 
      levels = 1:2,
      labels = c(
        "Male",
        "Female"
      )
      )
    ) %>%
  set_variable_labels(gender = "Gender")

frq(data$gender)
```

#### female

```{r}
frq(data$female)
```

#### age

```{r}
descr(data$age)
```

#### age_br

```{r}
data <- data %>%
  mutate(
    age_br = cut(
      age,
      breaks = c(17, 24, 34, 44, 54, Inf),
      labels = c("18-24", "25-34", "35-44", "45-54", "55 o +"),
      right = TRUE,
      include.lowest = TRUE
    )
  ) %>%
  set_variable_labels(age_br = "Age brackets")

frq(data$age_br)
```

#### educ

```{r}
frq(data$educ)
```

### Relación con los medios de producción 

#### sit_empleo

```{r,warning=FALSE,message=FALSE}
frq(data$a07)
```

#### relation_mop

```{r}
frq(data$relation_mop)
```

#### company_size

```{r}
frq(data$workplace_size)
```

#### workplace_size

```{r}
frq(data$workplace_size)
```

#### unions

```{r,warning=FALSE,message=FALSE}
frq(data$b19)

# Sindicatos en empresas
data <- data %>%
  mutate(
    unions = case_when(
      as.numeric(relation_mop) %in% c(1, 2) ~ NA_real_,
      as.numeric(relation_mop) == 3 & b19 == 1 ~ 1,
      as.numeric(relation_mop) == 3 & b19 %in% c(2, -888, -999) ~ 0,
      TRUE ~ NA_real_
    )
  ) %>%
  set_variable_labels(unions = "Union presence in company (1 = yes)") %>% 
  set_value_labels(unions = c(
    "Yes" = 1,
    "No" = 0
  )
  )
 
frq(data$unions)
```

#### union_member

```{r,warning=FALSE,message=FALSE}
frq(data$b21)

# Afiliación sindical
data <- data %>%
  mutate(
    union_member = case_when(
      as.numeric(relation_mop) %in% c(1, 2) ~ NA_real_,
      as.numeric(relation_mop) == 3 & b21 %in% c(1, 2) ~ 1,
      as.numeric(relation_mop) == 3 & b21 %in% c(3, -888, -999) ~ 0,
      unions == 0 ~ 0
    )) %>%
  set_variable_labels(union_member = "Union membership (1 = yes)") %>% 
  set_value_labels(union_member = c(
    "Yes" = 1,
    "No" = 0
  )
  )

frq(data$union_member)
```

### Políticas

#### c01_01

```{r}
# c01_01: Importancia: mejores salarios
frq(data$c01_01)

data <- data %>%
  mutate(
    c01_01 = ifelse(c01_01 %in% c(-999, -888), NA, c01_01)
  ) %>%
  set_variable_labels(c01_01 = "Level of importance of unions: in wages and working conditions (c01_01)")

frq(data$c01_01)
```

#### c01_02

```{r}
frq(data$c01_02)

data <- data %>%
  mutate(
    c01_02 = ifelse(c01_02 %in% c(-999, -888), NA, c01_02)
  ) %>%
  set_variable_labels(c01_02 = "Level of importance of unions: in reducing inequality (c01_02)")

frq(data$c01_02)
```

#### c05_02

```{r}
# c05_02: Acuerdo: desigualdad es porque dueños empresa pagan poco
frq(data$c05_02)

data <- data %>%
  mutate(
    c05_02 = ifelse(c05_02 %in% c(-999, -888), NA, c05_02)
  ) %>%
  set_variable_labels(c05_02 = "Level of agreement with: A major reason for high inequality in Chile is that business owners pay their workers little (c05_02)")

frq(data$c05_02)
```

#### c05_02_dummy

```{r}
# Crear variable dicotómica: acuerdo (4 o 5)
data <- data %>%
  mutate(
    c05_02_dummy = ifelse(
      c05_02 %in% c(4, 5), 1, 0)
    ) %>%
  set_variable_labels(c05_02_dummy = "Agree or Strongly agree: inequality exists because business owners pay too little") %>% 
  set_value_labels(c05_02_dummy = c(
    "Agree or Strongly agree (4,5)" = 1,
    "Disagree (1,2,3)" = 0
  ))

frq(data$c05_02_dummy)
```

#### c05_03

```{r}
# c05:03: Acuerdo: alto nivel vida dueños empresas es por pagar poco
frq(data$c05_03)

data <- data %>%
  mutate(
    c05_03 = ifelse(c05_03 %in% c(-999, -888), NA, c05_03)
  ) %>%
  set_variable_labels(c05_03 = "Level of agreement with: High standard of living for business owners is due to paying little (c05_03)")

frq(data$c05_03)
```

#### c05_03_dummy

```{r}
# Crear variable dicotómica: acuerdo (4 o 5)
data <- data %>%
  mutate(
    c05_03_dummy = ifelse(
      c05_03 %in% c(4, 5), 1, 0)
    ) %>%
  set_variable_labels(c05_03_dummy = "Agree or Strongly agree: High standard of living for business owners is due to paying little") %>% 
  set_value_labels(c05_03_dummy = c(
    "Agree or Strongly agree (4,5)" = 1,
    "Disagree (1,2,3)" = 0
  ))

frq(data$c05_03_dummy)
```

#### c06_02

```{r}
# c06_02: Acuerdo: apoyo sistema solidario de reparto
frq(data$c06_02)

data <- data %>%
  mutate(
    c06_02 = ifelse(c06_02 %in% c(-999, -888), NA, c06_02)
  ) %>%
  set_variable_labels(c06_02 = "Level of agreement with: support for the solidarity-based distribution system(c06_02)")

frq(data$c06_02)
```

#### c06_02_dummy

```{r}
# Crear variable dicotómica: acuerdo (4 o 5)
data <- data %>%
  mutate(
    c06_02_dummy = ifelse(
      c06_02 %in% c(4, 5), 1, 0)
  ) %>%
  set_variable_labels(c06_02_dummy = "Agree or Strongly agree: support for the solidarity-based distribution system") %>% 
  set_value_labels(c06_02_dummy = c(
    "Agree or Strongly agree (4,5)" = 1,
    "Disagree (1,2,3)" = 0
  ))

frq(data$c06_02_dummy)
```

#### c07_01

```{r}
# Acuerdo: aumentar impuestos a los más ricos
frq(data$c07_01)

data <- data %>%
  mutate(
    c07_01 = ifelse(c07_01 %in% c(-999, -888), NA, c07_01)
  ) %>%
  set_variable_labels(c07_01 = "Level of agreement with: Increase taxes on the wealthiest to fund social programs (c07_01)")

frq(data$c07_01)
```

#### c07_01_dummy

```{r}
# Crear variable dicotómica: acuerdo (4 o 5)
data <- data %>%
  mutate(
    c07_01_dummy = ifelse(
      c07_01 %in% c(4, 5), 1, 0)
  ) %>%
  set_variable_labels(c07_01_dummy = "Agree or Strongly agree: Increase taxes on the wealthiest to fund social programs") %>% 
  set_value_labels(c07_01_dummy = c(
    "Agree or Strongly agree (4,5)" = 1,
    "Disagree (1,2,3)" = 0
  ))

frq(data$c07_01_dummy)
```

#### c07_03

```{r}
# Acuerdo: sindicatos tengan más poder
frq(data$c07_03)

data <- data %>%
  mutate(
    c07_03 = ifelse(c07_03 %in% c(-999, -888), NA, c07_03)
  ) %>%
  set_variable_labels(c07_03 = "Level of agreement with: Implement laws to give unions more bargaining power (c07_03)")

frq(data$c07_03)
```

#### c07_03_dummy

```{r}
# Crear variable dicotómica: acuerdo (4 o 5)
data <- data %>%
  mutate(
    c07_03_dummy = ifelse(
      c07_03 %in% c(4, 5), 1, 0)
  ) %>%
  set_variable_labels(c07_03_dummy = "Agree or Strongly agree: Implement laws to give unions more bargaining power") %>% 
  set_value_labels(c07_03_dummy = c(
    "Agree or Strongly agree (4,5)" = 1,
    "Disagree (1,2,3)" = 0
  ))

frq(data$c07_03_dummy)
```

#### c07_04

```{r}
# Acuerdo: redistribuir riquezas
frq(data$c07_04)

data <- data %>%
  mutate(
    c07_04 = ifelse(c07_04 %in% c(-999, -888), NA, c07_04)
  ) %>%
  set_variable_labels(c07_04 = "Level of agreement with: Redistribute wealth from those with more resources to those with fewer resources (c07_04)")

frq(data$c07_04)
```

#### c07_04_dummy

```{r}
# Crear variable dicotómica: acuerdo (4 o 5)
data <- data %>%
  mutate(
    c07_04_dummy = ifelse(
      c07_04 %in% c(4, 5), 1, 0)
  ) %>%
  set_variable_labels(c07_04_dummy = "Agree or Strongly agree: Redistribute wealth from those with more resources to those with fewer resources") %>% 
  set_value_labels(c07_04_dummy = c(
    "Agree or Strongly agree (4,5)" = 1,
    "Disagree (1,2,3)" = 0
  ))

frq(data$c07_04_dummy)
```

#### c07_05

```{r}
# Acuerdo: igualdad hombres y mujeres
frq(data$c07_05)

data <- data %>%
  mutate(
    c07_05 = ifelse(c07_05 %in% c(-999, -888), NA, c07_05)
  ) %>%
  set_variable_labels(c07_05 = "Level of agreement with: Promote equality between men and women (c07_05)")

frq(data$c07_05)
```

#### c07_05_dummy

```{r}
# Crear variable dicotómica: acuerdo (4 o 5)
data <- data %>%
  mutate(
    c07_05_dummy = ifelse(
      c07_05 %in% c(4, 5), 1, 0)
  ) %>%
  set_variable_labels(c07_05_dummy = "Agree or Strongly agree: Promote equality between men and women") %>% 
  set_value_labels(c07_05_dummy = c(
    "Agree or Strongly agree (4,5)" = 1,
    "Disagree (1,2,3)" = 0
  ))

frq(data$c07_05_dummy)
```

#### c07_06

```{r}
# Acuerdo: educación universitaria pública
frq(data$c07_06)

data <- data %>%
  mutate(
    c07_06 = ifelse(c07_06 %in% c(-999, -888), NA, c07_06)
  ) %>%
  set_variable_labels(c07_06 = "Level of agreement with: Guarantee free public university education (c07_06)")

frq(data$c07_06)
```

#### c07_06_dummy

```{r}
# Crear variable dicotómica: acuerdo (4 o 5)
data <- data %>%
  mutate(
    c07_06_dummy = ifelse(
      c07_06 %in% c(4, 5), 1, 0)
  ) %>%
  set_variable_labels(c07_06_dummy = "Agree or Strongly agree: Guarantee free public university education") %>% 
  set_value_labels(c07_06_dummy = c(
    "Agree or Strongly agree (4,5)" = 1,
    "Disagree (1,2,3)" = 0
  ))

frq(data$c07_06_dummy)
```

### pol_id

```{r}
frq(data$c08)

data <- data %>%
  mutate(
    pol_id = case_when(
      c08 %in% c(0, 1, 2, 3) ~ 1,
      c08 %in% c(4, 5, 6) ~ 2,
      c08 %in% c(7, 8, 9, 10) ~ 3,
      c08 %in% c(11, 12, -888, -999) ~ 4,
      TRUE ~ NA_real_
    ),
    pol_id = factor(
      pol_id, 
      levels = 1:4, 
      labels = c(
        "Left", 
        "Center", 
        "Right", 
        "Not identified"
        ) 
      )
    ) %>%
  set_variable_labels(pol_id = "Political identification") 

frq(data$pol_id)
```

### politizado

```{r}
frq(data$c10_01)
frq(data$c15_01)

data <- data %>%
  mutate(
    politizado = if_else(
      c10_01 %in% c(4, 5) & c15_01 %in% c(3, 4, 5), 1, 0)
  ) %>% 
  set_variable_labels(politizado = "Politicized or non-politicized") %>% 
  set_value_labels(politizado = c(
    "Yes" = 1,
    "No" = 0
  ))

frq(data$politizado)
```

## Guardar datos

```{r}
saveRDS(data,file="output/data/data-cl-paperclar.rds")
```
